[package]
name = "urd"
version = "0.0.1"
edition = "2024"
description = "a lang [very WIP]"
license = "MIT"
repository = "https://github.com/metdxt/urd"

[dependencies]
ariadne = "0.6.0"
chumsky = { version="0.11.2", features=[ "pratt" ] }
logos = "0.15.1"
logos-display = "0.1.3"
thiserror = "2.0.17"

[profile.dev]
incremental=true

[lints]
clippy.unwrap_used = "deny"
clippy.expect_used = "deny"
rust.missing_docs = "warn"
