[package]
name = "urd"
version = "0.0.1"
edition = "2024"
description = "a lang [very WIP]"
license = "MIT"
repository = "https://github.com/metdxt/urd"

[dependencies]
chumsky = "0.11.2"
logos = "0.15.1"
